//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRube.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetRube.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为 null 或 empty。 的本地化字符串。
        /// </summary>
        public static string ArgumentNullOrEmptyException {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法确定类型 的本地化字符串。
        /// </summary>
        public static string CannotDetermineType {
            get {
                return ResourceManager.GetString("CannotDetermineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在索引 {0} 处未找到标记 的本地化字符串。
        /// </summary>
        public static string CouldNotFindTokenAtIndexException {
            get {
                return ResourceManager.GetString("CouldNotFindTokenAtIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零壹贰叁肆伍陆柒捌玖 的本地化字符串。
        /// </summary>
        public static string CurrencyDigital {
            get {
                return ResourceManager.GetString("CurrencyDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (￥_￥) 不好意思，数钱数晕了…… 的本地化字符串。
        /// </summary>
        public static string CurrencyOutOfRange {
            get {
                return ResourceManager.GetString("CurrencyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人民币 的本地化字符串。
        /// </summary>
        public static string CurrencyRMB {
            get {
                return ResourceManager.GetString("CurrencyRMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整元拾佰仟万拾佰仟亿拾佰仟角分负 的本地化字符串。
        /// </summary>
        public static string CurrencyUnit {
            get {
                return ResourceManager.GetString("CurrencyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按天 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByDay {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按半年 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByHalfYear {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByHalfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按小时 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByHour {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按分钟 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByMinute {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按月份 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByMonth {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按季度 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByQuarter {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按秒钟 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_BySecond {
            get {
                return ResourceManager.GetString("DateTimeCompareType_BySecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按周 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByWeek {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按年份 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_ByYear {
            get {
                return ResourceManager.GetString("DateTimeCompareType_ByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string DateTimeCompareType_None {
            get {
                return ResourceManager.GetString("DateTimeCompareType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光驱 的本地化字符串。
        /// </summary>
        public static string DriveType_CDRom {
            get {
                return ResourceManager.GetString("DriveType_CDRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定磁盘 的本地化字符串。
        /// </summary>
        public static string DriveType_Fixed {
            get {
                return ResourceManager.GetString("DriveType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络驱动器 的本地化字符串。
        /// </summary>
        public static string DriveType_Network {
            get {
                return ResourceManager.GetString("DriveType_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有根目录的驱动器 的本地化字符串。
        /// </summary>
        public static string DriveType_NoRootDirectory {
            get {
                return ResourceManager.GetString("DriveType_NoRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚拟磁盘 的本地化字符串。
        /// </summary>
        public static string DriveType_Ram {
            get {
                return ResourceManager.GetString("DriveType_Ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可移动磁盘 的本地化字符串。
        /// </summary>
        public static string DriveType_Removable {
            get {
                return ResourceManager.GetString("DriveType_Removable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string DriveType_Unknown {
            get {
                return ResourceManager.GetString("DriveType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在索引 {0} 处应为冒号 的本地化字符串。
        /// </summary>
        public static string ExpectedColonAtIndexException {
            get {
                return ResourceManager.GetString("ExpectedColonAtIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时 的本地化字符串。
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高 的本地化字符串。
        /// </summary>
        public static string MailPriorityHigh {
            get {
                return ResourceManager.GetString("MailPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低 的本地化字符串。
        /// </summary>
        public static string MailPriorityLow {
            get {
                return ResourceManager.GetString("MailPriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string MailPriorityNormal {
            get {
                return ResourceManager.GetString("MailPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string MessageType_Error {
            get {
                return ResourceManager.GetString("MessageType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string MessageType_Information {
            get {
                return ResourceManager.GetString("MessageType_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string MessageType_Success {
            get {
                return ResourceManager.GetString("MessageType_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string MessageType_Warning {
            get {
                return ResourceManager.GetString("MessageType_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下 的本地化字符串。
        /// </summary>
        public static string MoveDirection_Down {
            get {
                return ResourceManager.GetString("MoveDirection_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向左 的本地化字符串。
        /// </summary>
        public static string MoveDirection_Left {
            get {
                return ResourceManager.GetString("MoveDirection_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向右 的本地化字符串。
        /// </summary>
        public static string MoveDirection_Right {
            get {
                return ResourceManager.GetString("MoveDirection_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向上 的本地化字符串。
        /// </summary>
        public static string MoveDirection_Up {
            get {
                return ResourceManager.GetString("MoveDirection_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 类并不是 {1} 类的派生的 的本地化字符串。
        /// </summary>
        public static string NotSubclassException {
            get {
                return ResourceManager.GetString("NotSubclassException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        public static string OrderByType_ASC {
            get {
                return ResourceManager.GetString("OrderByType_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        public static string OrderByType_DESC {
            get {
                return ResourceManager.GetString("OrderByType_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下 的本地化字符串。
        /// </summary>
        public static string PositionType_Bottom {
            get {
                return ResourceManager.GetString("PositionType_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左下 的本地化字符串。
        /// </summary>
        public static string PositionType_BottomLeft {
            get {
                return ResourceManager.GetString("PositionType_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右下 的本地化字符串。
        /// </summary>
        public static string PositionType_BottomRight {
            get {
                return ResourceManager.GetString("PositionType_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间 的本地化字符串。
        /// </summary>
        public static string PositionType_Center {
            get {
                return ResourceManager.GetString("PositionType_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        public static string PositionType_Left {
            get {
                return ResourceManager.GetString("PositionType_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右 的本地化字符串。
        /// </summary>
        public static string PositionType_Right {
            get {
                return ResourceManager.GetString("PositionType_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 的本地化字符串。
        /// </summary>
        public static string PositionType_Top {
            get {
                return ResourceManager.GetString("PositionType_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上 的本地化字符串。
        /// </summary>
        public static string PositionType_TopLeft {
            get {
                return ResourceManager.GetString("PositionType_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上 的本地化字符串。
        /// </summary>
        public static string PositionType_TopRight {
            get {
                return ResourceManager.GetString("PositionType_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_Contains {
            get {
                return ResourceManager.GetString("QueryOperatorType_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以……结尾 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_EndsWith {
            get {
                return ResourceManager.GetString("QueryOperatorType_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_Equal {
            get {
                return ResourceManager.GetString("QueryOperatorType_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_GreaterThan {
            get {
                return ResourceManager.GetString("QueryOperatorType_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于或等于 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("QueryOperatorType_GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_LessThan {
            get {
                return ResourceManager.GetString("QueryOperatorType_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于或等于 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_LessThanOrEqual {
            get {
                return ResourceManager.GetString("QueryOperatorType_LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_NotEqual {
            get {
                return ResourceManager.GetString("QueryOperatorType_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以……开头 的本地化字符串。
        /// </summary>
        public static string QueryOperatorType_StartsWith {
            get {
                return ResourceManager.GetString("QueryOperatorType_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化对象时达到最大深度（{0}）限制 的本地化字符串。
        /// </summary>
        public static string SerializerEncounteredMaximumDepth {
            get {
                return ResourceManager.GetString("SerializerEncounteredMaximumDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        public static string TimeSpanDays {
            get {
                return ResourceManager.GetString("TimeSpanDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        public static string TimeSpanHours {
            get {
                return ResourceManager.GetString("TimeSpanHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫秒 的本地化字符串。
        /// </summary>
        public static string TimeSpanMilliseconds {
            get {
                return ResourceManager.GetString("TimeSpanMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        public static string TimeSpanMinutes {
            get {
                return ResourceManager.GetString("TimeSpanMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string TimeSpanSeconds {
            get {
                return ResourceManager.GetString("TimeSpanSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意外达到字符串的末尾 的本地化字符串。
        /// </summary>
        public static string UnexpectedlyReachedEndOfStringException {
            get {
                return ResourceManager.GetString("UnexpectedlyReachedEndOfStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在索引 {0} 处出现无法识别的标记 的本地化字符串。
        /// </summary>
        public static string UnrecognizedTokenAtIndexException {
            get {
                return ResourceManager.GetString("UnrecognizedTokenAtIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的 URL 无法访问（响应代码：{0}） 的本地化字符串。
        /// </summary>
        public static string UrlUnableAccess {
            get {
                return ResourceManager.GetString("UrlUnableAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
